### PR TITLE
Fix(parser)!: preserve each distinct CUBE/ROLLUP/GROUPING SET clause

### LINKED ISSUE #3979: incorrect combination of `rollup`  and `cube`
It looks like sqlglot is incorrectly combining `rollup`s into one list. Mixing multiple rollups, cubes and grouping sets all together is allowed in at least postgres and duckdb.

Here's an example using the [Palmer penguins data set](https://gist.githubusercontent.com/slopp/ce3b90b9168f2f921784de84fa445651/raw/4ecf3041f0ed4913e7c230758733948bc561f434/penguins.csv) with DuckDB, show that combining multiple rollups into one is not equivalent to separately specified rollups:

```
D create table t as from 'https://gist.githubusercontent.com/slopp/ce3b90b9168f2f921784de84fa445651/raw/4ecf3041f0ed4913e7c230758733948bc561f434/penguins.csv';
D table t limit 5;
┌───────┬─────────┬───────────┬────────────────┬───────────────┬───────────────────┬─────────────┬─────────┬───────┐
│ rowid │ species │  island   │ bill_length_mm │ bill_depth_mm │ flipper_length_mm │ body_mass_g │   sex   │ year  │
│ int64 │ varchar │  varchar  │    varchar     │    varchar    │      varchar      │   varchar   │ varchar │ int64 │
├───────┼─────────┼───────────┼────────────────┼───────────────┼───────────────────┼─────────────┼─────────┼───────┤
│     1 │ Adelie  │ Torgersen │ 39.1           │ 18.7          │ 181               │ 3750        │ male    │  2007 │
│     2 │ Adelie  │ Torgersen │ 39.5           │ 17.4          │ 186               │ 3800        │ female  │  2007 │
│     3 │ Adelie  │ Torgersen │ 40.3           │ 18            │ 195               │ 3250        │ female  │  2007 │
│     4 │ Adelie  │ Torgersen │ NA             │ NA            │ NA                │ NA          │ NA      │  2007 │
│     5 │ Adelie  │ Torgersen │ 36.7           │ 19.3          │ 193               │ 3450        │ female  │  2007 │
└───────┴─────────┴───────────┴────────────────┴───────────────┴───────────────────┴─────────────┴─────────┴───────┘
D select species, island, count(*) from t group by rollup (species), rollup (island);
┌───────────┬───────────┬──────────────┐
│  species  │  island   │ count_star() │
│  varchar  │  varchar  │    int64     │
├───────────┼───────────┼──────────────┤
│           │           │          344 │
│ Adelie    │ Torgersen │           52 │
│ Adelie    │ Biscoe    │           44 │
│ Chinstrap │           │           68 │
│           │ Dream     │          124 │
│           │ Torgersen │           52 │
│           │ Biscoe    │          168 │
│ Adelie    │           │          152 │
│ Chinstrap │ Dream     │           68 │
│ Gentoo    │           │          124 │
│ Adelie    │ Dream     │           56 │
│ Gentoo    │ Biscoe    │          124 │
├───────────┴───────────┴──────────────┤
│ 12 rows                    3 columns │
└──────────────────────────────────────┘
D select species, island, count(*) from t group by rollup (species, island);
┌───────────┬───────────┬──────────────┐
│  species  │  island   │ count_star() │
│  varchar  │  varchar  │    int64     │
├───────────┼───────────┼──────────────┤
│           │           │          344 │
│ Gentoo    │           │          124 │
│ Adelie    │           │          152 │
│ Chinstrap │           │           68 │
│ Adelie    │ Dream     │           56 │
│ Gentoo    │ Biscoe    │          124 │
│ Chinstrap │ Dream     │           68 │
│ Adelie    │ Torgersen │           52 │
│ Adelie    │ Biscoe    │           44 │
└───────────┴───────────┴──────────────┘
```

Here's what sqlglot does with this query:

```
In [3]: import sqlglot as sg

In [4]: sg.__version__
Out[4]: '25.16.1'

In [5]: sg.parse_one("select species, island, count(*) from t group by rollup (species), rollup (island)", read="duckdb").sql("duckdb")
Out[5]: 'SELECT species, island, COUNT(*) FROM t GROUP BY ROLLUP (species, island)'
```

### PR DESCRIPTION
**Pull request by georgesittas**
Fixes #3979

### CODE REVIEW

**Comment by cpcloud** [comment]
Very much appreciated! 🎉

File: tests/fixtures/pretty.sql [hunk 1]
```diff
@@ -99,14 +99,14 @@ WITH cte1 AS (
...
       x,
-    GROUPING SETS (
-      a,
-      (b, c)
-    ),
-    CUBE (
-      y,
-      z
-    )
+      GROUPING SETS (
```
Comment (tobymao) [inline tests/fixtures/pretty.sql:102]: why did the indentation change?

Comment (georgesittas) [reply tests/fixtures/pretty.sql:102]: I think I started with the same indentation but later changed it because `CUBE`, `ROLLUP` and `GROUPING SETS` are expressions corresponding to `GROUP BY` and not "query clauses" like `ORDER BY`, `HAVING` etc, which are currently in the same level as `SELECT`. It made more sense to indent them.

**Review by tobymao — APPROVED** [review]
