### PR TITLE
Fix: normalize before qualifying tables

### LINKED ISSUE #6167: Wrong qualification when selecting from CTE if casing does not match exactly
Considering a query where I select from a CTE and the casing matches exactly, when running `qualify` and setting a db, the result is correct.

```python
query = """
    with test as (
        select c1 from t1
    )
    select c1 from test
"""

parsed_query = qualify(
    sqlglot.parse_one(query, dialect="athena"),
    db="db",
)

# WITH "test" AS (
# SELECT
#     "t1"."c1" AS "c1"
# FROM "db"."t1" AS "t1"
# )
# SELECT
# "test"."c1" AS "c1"
# FROM "test" AS "test"
```

However, trying again but with the casing not exactly matching:

```python
query = """
    with tesT as ( -- notice the uppercase T in the CTE alias
        select c1 from t1
    )
    select c1 from test -- CTE name all in lowercase, still valid in case-insensitive dialects like Athena
"""

parsed_query = qualify(
    sqlglot.parse_one(query, dialect="athena"),
    db="db",
)

# WITH "test" AS (
# SELECT
#     "t1"."c1" AS "c1"
# FROM "db"."t1" AS "t1"
# )
# SELECT
# "test"."c1" AS "c1"
# FROM "db"."test" AS "test"
```

Notice that in the second case, the CTE reference `FROM "db"."test"` incorrectly includes the database qualifier, treating it as a table rather than recognizing it as the CTE.

### PR DESCRIPTION
**Pull request by georgesittas**
This [PR](https://github.com/tobymao/sqlglot/pull/4539) moved normalization after qualifying tables. It's been some time since then, but based on the linked issue at the time I think the motivation was to ensure aliases added by the latter rule are also normalized.

However, normalizing after table qualification is problematic because then we can't disambiguate tables from ctes and hence we may end up qualifying `Table` references with a db/catalog incorrectly.

This PR reinstates the original order and ensures that any aliases created by `_qualify_tables` are properly normalized.

Fixes #6167

### CODE REVIEW

File: tests/fixtures/optimizer/qualify_tables.sql [hunk 1]
```diff
@@ -42,7 +42,7 @@ SELECT 1 FROM c.y.z AS z, z.a;
 # title: bigquery implicit unnest syntax, coordinates.position should be a column, not a table
 # dialect: bigquery
 SELECT results FROM Coordinates, coordinates.position AS results;
-SELECT results FROM c.db.Coordinates AS Coordinates CROSS JOIN UNNEST(coordinates.position) AS results;
+SELECT results FROM c.db.Coordinates AS coordinates CROSS JOIN UNNEST(coordinates.position) AS results;
```
Comment (georgesittas) [inline tests/fixtures/optimizer/qualify_tables.sql:45]: Dunno why this was capitalized before, but I don't think it was right. E.g. the `position` column is qualified with the non-capitalized table. Aliases aren't case-sensitive in bigquery.
