### PR TITLE
Fix window parsing for ROWS BETWEEN without alias

### LINKED ISSUE #931: Window frame fails to parse
```
In [27]: import sqlglot as sg

In [28]: sg.__version__
Out[28]: '10.4.3'

In [29]: sg.parse_one("SELECT avg(x) OVER (ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) FROM t", read="duckdb")
...
ParseError: Expecting ). Line 1, Col: 26.
  SELECT avg(x) OVER (ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) FROM t
```

### PR DESCRIPTION
**Pull request by GeorgeSittas**
fixes #931

### CODE REVIEW

File: tests/fixtures/identity.sql [hunk 1]
```diff
@@ -426,6 +426,7 @@ SELECT SUM(x) OVER (PARTITION BY a RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT
 SELECT SUM(x) OVER (PARTITION BY a RANGE BETWEEN 1 AND 3)
 SELECT SUM(x) OVER (PARTITION BY a RANGE BETWEEN 1 FOLLOWING AND 3)
 SELECT SUM(x) OVER (PARTITION BY a RANGE BETWEEN 1 FOLLOWING AND UNBOUNDED FOLLOWING)
+SELECT AVG(x) OVER ( ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) FROM t
```
Comment (tobymao) [inline tests/fixtures/identity.sql:429]: this means the generator is not correct, it has a space in it

Comment (GeorgeSittas) [reply tests/fixtures/identity.sql:429]: fixing it

Comment (GeorgeSittas) [reply tests/fixtures/identity.sql:429]: done
